java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/civil/sdt-gateway:latest'
  ingressHost: civil-sdt-gateway-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    civil:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
